"""Guard the pandapower/grid-JSON compatibility contract.

These tests exist because of a genuinely nasty failure mode discovered in
Aug 2026 while pinning dependencies.

The stored grid JSONs use the *split* ZIP-load columns
(``const_z_p_percent`` / ``const_i_p_percent``) that pandapower introduced
in 3.2. On pandapower 3.1.x, ``runpp()`` looks for the older combined
``const_z_percent`` column and raises ``KeyError``.

That would be fine if it were loud. It isn't: the continuation solver in
``socal_grid.dispatch_and_run.run()`` wraps every ``runpp`` call in
``except Exception`` and reports the step as non-convergent. So an
incompatible pandapower does not crash the run -- it produces a complete,
plausible-looking experiment in which the power flow never solves, no load
is ever shed, and every grid KPI is exactly zero.

An all-zero reward column is easy to mistake for "the agent didn't learn
anything yet", which is why this needs a test rather than vigilance.
"""

from __future__ import annotations

import json
import os

import pytest

# The lightweight `unit` CI stage installs numpy/pandas/scipy only, so this
# module must stay collectable without pandapower. Everything that needs it is
# marked `slow` and runs in the `system` stage, which installs the real
# requirements.
pp = pytest.importorskip("pandapower", reason="pandapower not installed")

pytestmark = pytest.mark.slow

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GRID_JSONS = [
    "socal_grid/socal_grid.json",
    "midas_socal/socal_grid_midas.json",
    "midas_socal/socal_grid_midas_rescaled.json",
    "midas_socal/palisades_grid_midas_rescaled.json",
]

# The split ZIP-load columns. Their presence is what requires pandapower >= 3.2.
SPLIT_ZIP_COLUMNS = {
    "const_z_p_percent",
    "const_i_p_percent",
    "const_z_q_percent",
    "const_i_q_percent",
}


def _minimum_pandapower_version() -> tuple[int, int]:
    return (3, 2)


def test_pandapower_is_new_enough_for_the_stored_grids():
    """pandapower must understand the split ZIP-load column names."""
    major, minor = (int(p) for p in pp.__version__.split(".")[:2])
    assert (major, minor) >= _minimum_pandapower_version(), (
        f"pandapower {pp.__version__} is too old for the stored grid JSONs, "
        "which use the split ZIP-load columns introduced in 3.2. On older "
        "releases runpp() raises KeyError('const_z_percent'), which "
        "dispatch_and_run silently swallows as non-convergence -- every grid "
        "KPI then reads zero instead of failing. See requirements.txt."
    )


def test_runpp_accepts_the_zip_load_columns():
    """The installed pandapower must actually solve a net carrying them.

    A version check alone is not enough: this asserts the behaviour rather
    than the version number, so a future rename is caught too.
    """
    net = pp.create_empty_network()
    b0 = pp.create_bus(net, vn_kv=20.0)
    b1 = pp.create_bus(net, vn_kv=20.0)
    pp.create_ext_grid(net, bus=b0, vm_pu=1.0)
    pp.create_line(
        net, from_bus=b0, to_bus=b1, length_km=1.0, std_type="NAYY 4x50 SE"
    )
    pp.create_load(net, bus=b1, p_mw=0.01, q_mvar=0.005)

    for column in SPLIT_ZIP_COLUMNS:
        assert column in net.load.columns, (
            f"pandapower {pp.__version__} does not create '{column}' on "
            "net.load; the stored grid JSONs will not round-trip."
        )

    pp.runpp(net)
    assert net["converged"]


@pytest.mark.parametrize("rel_path", GRID_JSONS)
def test_stored_grid_json_uses_split_zip_columns(rel_path):
    """Document which column flavour each stored grid actually carries.

    If a grid is ever regenerated by an older pandapower this flips, and the
    minimum-version test above would then be guarding the wrong thing.
    """
    path = os.path.join(REPO_ROOT, rel_path)
    if not os.path.exists(path):
        pytest.skip(f"{rel_path} not present in this checkout")

    with open(path) as handle:
        raw = json.load(handle)

    load = raw["_object"]["load"]
    obj = load["_object"]
    if isinstance(obj, str):
        obj = json.loads(obj)
    columns = set(obj["columns"])

    assert SPLIT_ZIP_COLUMNS <= columns, (
        f"{rel_path} is missing {sorted(SPLIT_ZIP_COLUMNS - columns)}. "
        "If this grid was regenerated with pandapower < 3.2, revisit the "
        "version contract in requirements.txt."
    )
    assert "const_z_percent" not in columns


def test_grid_json_loads_and_solves():
    """End-to-end: the real grid deserialises and the power flow converges.

    This is the check that would have caught the 3.1.2 regression directly.
    """
    path = os.path.join(REPO_ROOT, "socal_grid/socal_grid.json")
    if not os.path.exists(path):
        pytest.skip("socal_grid.json not present in this checkout")

    net = pp.from_json(path)
    assert len(net.load) > 0
    for column in SPLIT_ZIP_COLUMNS:
        assert column in net.load.columns

    # The raw net is deliberately under-built (it is strengthened and
    # dispatched before use), so we do not assert convergence here -- only
    # that runpp gets far enough to fail on physics rather than on a missing
    # column. A KeyError is the regression; non-convergence is not.
    try:
        pp.runpp(net, calculate_voltage_angles=True, enforce_q_lims=False)
    except KeyError as exc:  # pragma: no cover - this is the regression
        pytest.fail(
            f"runpp raised KeyError({exc}) on the stored grid -- this is the "
            "pandapower ZIP-load column incompatibility. See requirements.txt."
        )
    except Exception:
        pass
