"""Generate the four arms of the whitelist validation from ONE source file.

Why generate rather than hand-write four YAMLs
----------------------------------------------
The claim under test is "the arms are identical except for the whitelist".
Hand-maintained copies make that a promise; generating all of them from
``experiment_eaton_firefighting_moo.yml`` and applying exactly one documented
mutation per arm makes it a property of the build. ``--check`` re-derives the
files and fails if they drifted, so the promise stays true.

The arms
--------
``off``   4 scripted phases x 60 steps, no whitelist.               baseline
``off2``  byte-identical to ``off`` except its run uid.             determinism control
``on``    ``off`` + keep_sensors/keep_actuators on socal_grid.      the treatment
``neg``   ``off`` at 8 steps with raster_seed 47 -> 48.             sensitivity control

Every arm drops the ``grid_probe`` agent. Its ``DummyMuscle`` calls
``actuator.space.sample()`` on a gymnasium ``Box`` seeded from OS entropy, so a
run containing it is not reproducible against itself and NO comparison between
any two arms would mean anything. Removing it is safe: palaestrAI only requires
that every uid an agent subscribes to exists, never that every environment
sensor or actuator is subscribed -- tens of thousands already go unassigned.

The ``neg`` pair stays short on purpose: showing the comparator can detect a
difference takes a handful of steps, not an hour. It needs its OWN 8-step
baseline (``negb``) rather than being compared against the 60-step ``off`` arm
-- that comparison would report a divergence caused by the differing step
count, which demonstrates nothing about sensitivity to the physics.

Why the perturbation is ``base_speed`` and not ``raster_seed``
--------------------------------------------------------------
The first version of this control changed ``raster_seed``. It appeared to work
-- DIVERGENCE FOUND on all four phases -- but for the wrong reason. With
``use_real_dem: true`` the DEM is real and fuel classes 0-5 are derived
deterministically from elevation (``gis._fuel_from_dem``); the seed's ONLY
effect is the 3%% house scatter. So the fire was identical and the comparator
tripped on ``houses_total`` (101 vs 123) at step 0, breaking out before it
compared a single ``cell_state`` hash or load reading. It validated the scalar
channel and left the two that carry the equivalence claim untested.

``base_speed`` drives the perimeter-informed per-cell wind field, so it changes
the rate of spread in every burning cell from the first step, with the terrain
and the house count held identical. Any divergence it produces therefore has to
come through the fire-state hash and the loads downstream of it -- exactly the
channels the whitelist result depends on. (The scalar ``wind_speed`` params
cannot be used: when a per-cell wind field is active ``WildfireDriver.set_wind``
returns early and they are inert.)

Usage
-----
    python analysis/make_whitelist_configs.py            # write the files
    python analysis/make_whitelist_configs.py --check    # verify, do not write
"""
from __future__ import annotations

import argparse
import copy
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(
    ROOT, "palaestrai_socal", "experiment_eaton_firefighting_moo.yml"
)
OUT_DIR = os.path.join(ROOT, "palaestrai_socal")

#: Identical to both the 8-step check and the production
#: experiment_eaton_firefighting_moo.yml, so all three answer the same question.
#: The bus/health patterns are redundant once grid_probe is gone; they stay for
#: that comparability.
KEEP_SENSORS = [
    "Powergrid-0.0-load-*.p_mw",
    "Powergrid-0.0-bus-*.vm_pu",
    "Powergrid-0.0-line-*.p_from_mw",
    "Powergrid-0.Grid-0.health",
]
KEEP_ACTUATORS = ["Powergrid-0.0-load-*.p_mw"]

HEADER = """# =============================================================================
# WHITELIST VALIDATION -- arm: {arm}
#
# GENERATED by analysis/make_whitelist_configs.py from
# experiment_eaton_firefighting_moo.yml. Do not hand-edit: run the generator,
# or `--check` in CI will flag the drift. Editing one arm by hand is exactly
# how an "identical except X" comparison silently stops being one.
#
# {what}
#
# grid_probe is removed from every arm (its DummyMuscle samples an OS-entropy
# seeded Box, which makes any run non-reproducible against itself).
# =============================================================================
"""

WHAT = {
    "off": "Baseline: no whitelist, 4 scripted phases x 60 steps.",
    "off2": "Determinism control: identical to the off arm but for the run uid. "
            "Must come out bit-identical to it, or nothing else is interpretable.",
    "on": "Treatment: the off arm plus keep_sensors/keep_actuators on socal_grid. "
          "This is the only difference from off.",
    "onb": "Timing probe: the on arm truncated to 8 steps. With off/on/negb it "
           "separates per-phase startup cost from per-step cost.",
    "negb": "Sensitivity baseline: the off arm truncated to 8 steps. Exists only "
            "to give the neg arm a same-length partner to be compared against.",
    "neg": "Sensitivity control: negb with the fire driver's base_speed 14 -> 14.5 "
           "(terrain and house count held identical). MUST diverge from negb, "
           "through the fire-state hash -- it proves the comparator can see a "
           "change in the trajectory itself.",
}


def _phases(doc):
    for phase in doc["schedule"]:
        (name, body), = phase.items()
        yield name, body


def _env(body, uid):
    for e in body.get("environments", []):
        if e["environment"].get("uid") == uid:
            return e["environment"].setdefault("params", {})
    return None


def build(arm: str) -> dict:
    doc = copy.deepcopy(yaml.safe_load(open(SOURCE)))
    doc["uid"] = f"socal_v08_wlval_{arm}"

    for _name, body in _phases(doc):
        body["agents"] = [
            a for a in body.get("agents", []) if a.get("name") != "grid_probe"
        ]
        grid = _env(body, "socal_grid")
        # NB: "onb" is the whitelisted arm too -- it is "on" truncated to 8
        # steps. Testing `arm == "on"` here silently produced a second copy of
        # the un-whitelisted 8-step arm, which then "measured" a whitelisted
        # per-step cost of roughly zero.
        if arm in ("on", "onb"):
            grid["keep_sensors"] = list(KEEP_SENSORS)
            grid["keep_actuators"] = list(KEEP_ACTUATORS)
        else:
            # The SOURCE file already ships the whitelist -- it is the current
            # production config. The un-whitelisted arms must therefore REMOVE
            # it explicitly; inheriting it silently would make "off" identical
            # to "on" and the whole comparison vacuous. (This is not
            # hypothetical: the first draft of this generator did exactly that,
            # and only the off-vs-on config diff caught it.)
            grid.pop("keep_sensors", None)
            grid.pop("keep_actuators", None)
        if arm in ("neg", "negb", "onb"):
            gis = _env(body, "gis_world")
            gis["max_steps"] = 8
            grid["max_steps"] = 8
            # end = max_steps * step_size, matching the source file's ratio
            grid["end"] = 8 * int(grid.get("step_size", 3600))
        if arm == "neg":
            for a in body["agents"]:
                if a["name"] == "wildfire":
                    a["muscle"]["params"]["base_speed"] = 14.5
    return doc


def render(arm: str) -> str:
    return HEADER.format(arm=arm.upper(), what=WHAT[arm]) + yaml.safe_dump(
        build(arm), sort_keys=False, default_flow_style=False, width=100
    )


def path_for(arm: str) -> str:
    return os.path.join(OUT_DIR, f"experiment_wlval_{arm}.yml")


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="verify the files match the generator; write nothing")
    ns = p.parse_args(argv)

    rc = 0
    for arm in ("off", "off2", "on", "onb", "negb", "neg"):
        text, dest = render(arm), path_for(arm)
        if ns.check:
            have = open(dest).read() if os.path.exists(dest) else None
            state = "OK" if have == text else "DRIFTED"
            rc |= 0 if have == text else 1
            print(f"  {os.path.basename(dest):32s} {state}")
        else:
            open(dest, "w").write(text)
            print(f"  wrote {os.path.basename(dest)}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
